// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acmmuhybijjkycfoxuzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbW11aHliaWpqa3ljZm94dXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NzU2MTUsImV4cCI6MjA1MDQ1MTYxNX0.xHQppR6Sd9DZYraFpKA353JZwqwD7xPSxPz6TzhE8rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);